### ISSUE TITLE
Change links from 'navigation.ros.org' to 'docs.nav2.org'

### ISSUE THREAD

**Issue by dgel27** [turtlebot/turtlebot4-user-manual#23]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

1.0.0

### Expected behaviour

The links to navigation.ros.org need replace to new address nav2.org and docs.nav2.org/xxxxxx
The 4 times in the manual:
[overview/resources.md],
[tutorials/navigation.md],
[tutorials/turtlebot4_navigator.md] 

### Actual behaviour

The link doesn't open

### To Reproduce

click on the link

**Comment by civerachb-cpr** [comment]
This is addressed in https://github.com/turtlebot/turtlebot4-user-manual/pull/26 and should (hopefully) be corrected soon.

**Comment by civerachb-cpr** [comment]
This is now fixed on the live documentation.  Thanks for bringing it to our attention!
