### ISSUE TITLE
keyboard teleop instuction needs remap in jazzy

### ISSUE THREAD

**Issue by mdxtinkernick** [turtlebot/turtlebot4-user-manual#27]
### Robot Model

Turtlebot4 Lite

### ROS distro

Jazzy

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

v 2.0.0 of TurtleBot user manual

### Expected behaviour

running the command on line 47 in tutorials/driving.md should enable keystrokes to move the robot move, but the topic it now needs to publish on is now cmd_vel_unstamped, so the command should include

--ros-args -r cmd_vel:=cmd_vel_unstamped

not sure whether the line should be just edited in place, or added as an additional line within jazzy statements, so have not submitted a pull request

also line 88. ros2 topic pub /cmd_vel geometry_msgs/msg/Twist \.     cmd_vel should also be cmd_vel_unstamped

### Actual behaviour

robot does not move

### To Reproduce

follow instructions in tutorial in jazzy up to the line 

ros2 run teleop_twist_keyboard teleop_twist_keyboard

**Comment by civerachb-cpr** [comment]
Thanks for bringing this to our attention. I've made a change to the manual to specify that the `stamped` parameter should be set to `true`, rather than remapping the topic.

Unstamped messages are deprecated in Jazzy, and may eventually be removed, so using the original topic but publishing stamped messages is preferable.

**Comment by mdxtinkernick** [comment]
That makes more sense.

The command at line 88 needs this amending for jazzy as well

**Comment by civerachb-cpr** [comment]
The command on line 88 of `driving.md`?
```
ros2 launch turtlebot4_bringup joy_teleop.launch.py
```

This command should be correct for Jazzy already; the necessary parameter to use stamped messages is set [in the launch file](https://github.com/turtlebot/turtlebot4_robot/blob/28e115f86930bb3273f1a1aa4738dbd8747513f0/turtlebot4_bringup/launch/joy_teleop.launch.py#L68), so assuming you have the Jazzy branch checked-out already you should automatically get stamped messages for joystick teleoperation.

**Comment by civerachb-cpr** [comment]
Oh, sorry. The old line 88. Unfortunate coincidence that both before & after the change I made have commands on them.
