### ISSUE TITLE
Dead udev rules link

### ISSUE THREAD

**Issue by s10az** [turtlebot/turtlebot4-user-manual#3]
I was looking at [sensors page](https://turtlebot.github.io/turtlebot4-user-manual/software/sensors.html) and tried to look for the udev rules for RPLIDAR.

> If the [udev rules](https://github.com/turtlebot/turtlebot4-images/blob/galactic/turtlebot4_setup/udev/turtlebot4.rules) are installed, the RPLIDAR will appear as /dev/RPLIDAR. Otherwise it will be /dev/ttyUSB0.

But the link seems to be dead.

**Comment by tonybaltovski** [comment]
For galatic here is the link: https://github.com/turtlebot/turtlebot4_setup/blob/galactic/udev/turtlebot4.rules
