### ISSUE TITLE
Imu topic status= Frequency to high

### ISSUE THREAD

**Issue by JJJ2777** [turtlebot/turtlebot4-user-manual#6]
Where or how can I change the frequency of my IMU-Sensor?

I'm using ROS2 on my PC with Ubuntu 20.04 and I have the Turtlebot4 with the Create3 Version and the Raspberry Pi 4.

In the pictures you can see the diagnostic window from my Turtlebot4 with the warning about my IMU-Sensor.

I call the diagnostic window with:
`ros2 launch turtlebot4_viz view_diagnostics.launch.py`

![Bildschirmfoto_2023-04-28_10-52-12](https://user-images.githubusercontent.com/132054089/235104011-834787dd-d57f-4e39-af1f-a0ff45e6e509.jpg)
![Bildschirmfoto_2023-04-28_10-49-34](https://user-images.githubusercontent.com/132054089/235104037-0ddccdd2-d5bd-4483-ad15-703d03322780.jpg)

**Comment by roni-kreinin** [comment]
The IMU frequency was updated as part of the Humble update for Create 3. You cannot change the frequency but 100Hz is correct. This warning can be ignored and will be fixed in the diagnostics.
